Information:
  Title: "Hack's blog"
  Icon: icon.png
  Description: I am Hack, I build cool shit, probably in rust
  Link: github.com/hackedos
  Theme: CatppuccinMocha

Connections:
  GitHub: hackedos
  Discord: hackos
